config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "peliculas#index"
  # get "peliculas", to: "peliculas#index"
  # post "peliculas", to: "peliculas#create"
  # get "peliculas/new", to: "peliculas#new", as: :new
  # delete "peliculas/:id", to: "peliculas#destroy",as: :delete
  # get "peliculas/:id", to: "peliculas#show", as: :pelicula


  # get "peliculas/:id/edit", to: "peliculas#edit", as: :edit
  # patch "peliculas/:id", to: "peliculas#update"
  resources :peliculas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pelicula.rb
class Pelicula < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/peliculas_controller.rb
class PeliculasController < ApplicationController
  before_action :set_pelicula, only: [:edit, :update, :show, :destroy]
  def index
    @peliculas = Pelicula.all  
  end

  def show
  end

  def new
    @pelicula = Pelicula.new
    @category = ["chinese", "italian", "japanese", "french", "belgian"]

  end

  def create 
    @pelicula = Pelicula.create(pelicula_params)
    @pelicula.save

    redirect_to pelicula_path(@pelicula)
  end

  def edit
    @category = ["chinese", "italian", "japanese", "french", "belgian"]
  end

  def update
    @pelicula.update(pelicula_params)
    redirect_to pelicula_path
  end

  def destroy
    @pelicula.destroy
    redirect_to peliculas_path
  end
  private

  def pelicula_params
    params.require(:pelicula).permit(:name, :genero)  
  end

  def set_pelicula
    @pelicula = Pelicula.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/peliculas_helper.rb
module PeliculasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeliculasReseAs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/peliculas/_form.html.erb
<%= form_for(pelicula) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.select :genero, @category, :prompt => 'Select One' %>
  <%= f.submit %>
<% end %>

app/views/peliculas/edit.html.erb
<%= render "form", pelicula: @pelicula %>

app/views/peliculas/index.html.erb
<h1>Peliculas</h1>
<%= link_to 'Crear', new_pelicula_path %>
<ul>
<% @peliculas.each do |pelicula| %>
  <li><%= link_to pelicula.name, pelicula_path(pelicula.id) %></li>
<% end %>
</ul>

app/views/peliculas/new.html.erb
<%= render "form", pelicula: @pelicula %>

app/views/peliculas/show.html.erb
<h1><%= @pelicula.name %></h1>
<h2><%= @pelicula.genero %></h2>


<%= link_to "Editar", edit_pelicula_path(@pelicula) %>
<%= link_to "Eliminar",
            pelicula_path(@pelicula),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
<%= link_to "Home", peliculas_path %>
<%# <%= link_to "Añadir Reseña", new_restaurant_review_path(@restaurant) %> 